version: '3.1'

services:
    # --------------------------------------------------------------
    #
    #    Change this if your want use your own application.
    #    It's very important expose your application in port 5442
    #    and use the http protocol.
    #
    #    Default Application
    #
    #    Openvidu-Call Version: 2.28.0
    #
    # --------------------------------------------------------------
    app-client:
        image: openvidu/openvidu-react-demo:1.2
        restart: on-failure
        network_mode: host
        environment:
            - SERVER_PORT=3000
            - OPENVIDU_URL=http://i9a203.p.ssafy.io:5443
            - OPENVIDU_SECRET=${OPENVIDU_SECRET}
        logging:
            options:
                max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
